.TH POC-CONSOLE "1" "June 2021" "Manual page for poc-console"
.\"
.\" 22st June 2021
.\" Man page author:
.\"   Tian Qiao <abcnsxyz@gmail.com>
.\"
.SH NAME
.I poc-console
\- console mode of
.B pocsuite3.
.SH Legal Disclaimer
poc-console is part of pocsuite3. Usage of pocsuite3 for attacking targets without prior mutual consent is illegal.
pocsuite3 is for security testing purposes only.
.SH SYNOPSIS
.B poc-console
.SH DESCRIPTION
.I poc-console is the console mode of pocsuite3.
.I pocsuite3
is an open-sourced remote vulnerability testing and proof-of-concept
development framework developed by the Knownsec 404 Team. It comes with a
powerful proof-of-concept engine, many nice features for the ultimate
penetration testers and security researchers.
.SH OPTIONS
poc-console do not have command line options. To see a list of available commands,
enter help at the console prompt.
.SH "SEE ALSO"
The full documentation for
.B pocsuite3
is maintained at:
.br
.I https://github.com/knownsec/pocsuite3/blob/master/docs/USAGE.md
.PP
.SH VERSION
This manual page documents pocsuite3 version 1.8.10
.SH AUTHOR
.br
(c) 2014-2021 by Knownsec 404 Team
.br
<404-team@knownsec.com>
.LP
This program is free software; you may redistribute and/or modify it under
the terms of the GNU General Public License as published by the Free
Software Foundation; Version 2 with the clarifications and
exceptions described below. This guarantees your right to use, modify, and
redistribute this software under certain conditions. If you wish to embed
pocsuite3 technology into proprietary software, we sell alternative licenses
(contact 404-team@knownsec.com).
.PP
Manual page started by Tian Qiao
<abcnsxyz@gmail.com>
.PP

